### ISSUE TITLE
Use different VRID's in different namespaces

### ISSUE THREAD

**Issue by mikecurrancs** [aledbf/kube-keepalived-vip#114]
I am sure that his is answered somewhere, but I have not found where just yet. 

Is it possible to input different VRIDs as part of instantion with kuberneetes or only if we choose to build our own versions of the container from the source?

I am assuming the latter, just looking for confirmation.

Thanks
Mike Curran

**Comment by aledbf** [comment]
> I am assuming the latter, just looking for confirmation.

Correct.

**Comment by mikecurrancs** [comment]
Thank you, I will close this down.
