### ISSUE TITLE
Error while doing a GO get

### ISSUE THREAD

**Issue by panigrahis** [aledbf/kube-keepalived-vip#16]
Hi I am getting error while doing a go get on the GIT repo
soumya@soumyapanigrahi-ubuntu-virtual-machine:~/go/src/github.com/aledbf/kube-keepalived-vip$ go get -d github.com/aledbf/kube-keepalived-vipcan't load package: package github.com/aledbf/kube-keepalived-vip: no buildable Go source files in /home/soumya/go/src/github.com/aledbf/kube-keepalived-vip

soumya@soumyapanigrahi-ubuntu-virtual-machine:~/go/src/github.com/aledbf/kube-keepalived-vip$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/soumya/go"
GORACE=""
GOROOT="/usr/lib/go-1.8"
GOTOOLDIR="/usr/lib/go-1.8/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build258738998=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

**Comment by aledbf** [comment]
Closing. Please clone the repository and run `make`
