### ISSUE TITLE
VRID flag not supported in keepalived.tmpl

### ISSUE THREAD

**Issue by primeroz** [aledbf/kube-keepalived-vip#18]
https://github.com/aledbf/kube-keepalived-vip/blob/9b6086be592a4e51696c62c36f0c5b492375ef4e/rootfs/keepalived.tmpl#L18

Unless i misunderstand how this is supposed to work it seem that the _vrid_ flag passed to keepalived-vip container is not expanded in the template which is enforcing _50_

**Comment by aledbf** [comment]
@primeroz please download `aledbf/kube-keepalived-vip:0.20`

**Comment by primeroz** [comment]
Seems like the template is not expanding properly for me anymore 

    ERROR: logging before flag.Parse: F0920 16:10:19.771428       1 main.go:392] Error loading templates: template: keepalived.tmpl:80: unexpected EOF

Do we need an extra "{{ end }}" to the _if_ added here ? 
https://github.com/aledbf/kube-keepalived-vip/blob/4c3501074d0a7c1ed4e0ba754e45b72b31a342b2/rootfs/keepalived.tmpl#L54
