### ISSUE TITLE
Kubernetes services exposing host(worker) ports

### ISSUE THREAD

**Issue by walteraa** [aledbf/kube-keepalived-vip#21]
**What is the problem?**

When I create a kubernetes public service(reached from the internet), all host ports are being exposed through the kubernetes IP service, not only using the port used in the kubernetes service.

**How it should work?**

Having a host having `150.165.A.B` as IP address accessible through ssh over 22 port and creating a public kubernetes service which has `150.165.C.E` as IP address exposing web servers over 80 port: 

* I should be able to perform:
  * `$ ssh walteraa@150.165.A.B` [OK]
  * `$ curl 150.165.C.E` [OK]
* I shouldn't be able to perform:
  * `$ ssh walteraa@150.165.C.E` [FAIL]
  * `$ curl 150.165.A.B` [OK]

 
**How to reproduce the problem:**

Once I create a service and the VIP is added in the `virtual_address`, the virtual IP added in the managed interface, is responding to all processes that the host IP responds. For example:

Imagine a worker node that has 150.165.A.B as IP, and I'm able to connect this host through `ssh` 
e.g.: `$ ssh walteraa@150.165.A.B`

And I have configured the `keepalived-cloud-provider` to create service using `150.165.C.D/27` CIDR. 

Consider that the service creation process will create a service which has `150.165.C.E` as IP address, this will generate a `keepalived.conf` a file similar to the following

```conf
global_defs {
  vrrp_version 3
  vrrp_iptables KUBE-KEEPALIVED-VIP
}
vrrp_instance vips {
  state BACKUP
  interface eth0
  virtual_router_id 50
  priority 100
  nopreempt
  advert_int 1
  track_interface {
    eth0
  }
  virtual_ipaddress {
    150.165.C.E
  }

# Service: app-my-service
virtual_server  150.165.C.E 80 {
  delay_loop 5
  lvs_sched rr
  lvs_method NAT
  persistence_timeout 1800
  protocol TCP
  real_server 192.168.104.57 80 {
    weight 1
    TCP_CHECK {
      connect_port 80
      connect_timeout 3
    }
  }
}
```

It will manage host's network interface like that

```bash
$ sudo ip addr list eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:26:b9:51:bf:79 brd ff:ff:ff:ff:ff:ff
    inet 150.165.A.A/27 brd 105.156.A.E scope global eth0
       valid_lft forever preferred_lft forever
    inet 150.165.C.E/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::226:b9ab:fe15:ba97/64 scope link
       valid_lft forever preferred_lft forever
```
After having this setup, you should be able to reproduce the scenarios described above.

Is missing any firewall rule to avoid kubernetes services which are using keepalived expose the real host services/ports?

**Comment by steven-sheehy** [comment]
Don't think this is a kube-keepalived-vip concern. It just creates a virtual IP that routes to the underlying host IP that it is assigned to. This uses purely layer 2 ARP broadcasts to advertise that the VIP can be reached by the same MAC address that the host IP has. Thus any port that is exposed on the host will be exposed on the VIP. You can just add all ports you don't want exposed to the firewall. Or use a load balancer like MetalLB or from your cloud provider.

**Comment by walteraa** [comment]
I realized that is doesn't work because I was running Kubernetes behind OpenStack and neutron doesn't make possible using virtual IPs in the way that `kube-keepalived` does. I Fixed it running the cluster in a baremetal.
