### ISSUE TITLE
Services only deploy on master with keepalived inside my cluster

### ISSUE THREAD

**Issue by Theoooooo** [aledbf/kube-keepalived-vip#27]
Hello,
I'm using a cluster with a master and a slave. Without keepalived running, my services deploy on the server who have the lowest activity (LoadBalancing). 

After configuring the configmap and the mail .yml file, every services i deploy only deploy on the master.
The virtual IP work correctly and i add a label on my both server to allow keepalived to work on the both servers.

If you have any idea why i got this problem, let me know

**Comment by steven-sheehy** [comment]
kube-keepalived-vip has nothing to do with where pods get scheduled. It only creates a VIP and assigns it to a service. kube-scheduler in kube-system namespace decides where pods are placed. This can be closed.
