### ISSUE TITLE
Question: Where to find source of  image aledbf/haproxy-self-reload?

### ISSUE THREAD

**Issue by elemental-lf** [aledbf/kube-keepalived-vip#30]
Hello there,

in https://github.com/aledbf/kube-keepalived-vip/blob/master/vip-daemonset-proxy.yaml there is a reference to an image on Docker Hub: aledbf/haproxy-self-reload. Where can I find the source code for this image? A Google search didn't yield anything useful unfortunately.

Thanks!
LF.

**Comment by aledbf** [comment]
@elemental-lf I will add the source code for that image in this repository

**Comment by elemental-lf** [comment]
Sounds good, thank you!

**Comment by aledbf** [comment]
This is the repository https://github.com/aledbf/haproxy-self-reload
