### ISSUE TITLE
Interest in Helm chart for kube-keepalived-vip?

### ISSUE THREAD

**Issue by elemental-lf** [aledbf/kube-keepalived-vip#33]
Would you be interested in including a Helm chart for kube-keepalived-vip? Current work is at https://github.com/elemental-lf/chart-kube-keepalived-vip. It supports both the normal and the PROXY protocol setup.

**Comment by aledbf** [comment]
@elemental-lf sure

**Comment by elemental-lf** [comment]
@aledbf Great! Please tell me in which subdirectory you want the chart to live. Something like chart or helm-chart? After we've agreed on something I'll integrate the chart and file a pull request.

**Comment by aledbf** [comment]
@elemental-lf `chart`?
