### ISSUE TITLE
Add LoadBalancer support

### ISSUE THREAD

**Issue by steven-sheehy** [aledbf/kube-keepalived-vip#43]
We're using kube-keepalived-vip in combination with [keepalived-cloud-provider](https://github.com/munnerz/keepalived-cloud-provider) to provision keepalived based loadbalancers for on premise kubernetes. The way we configure it, it even supports [multiple services](#12) behind a single VIP. Is there any interest in combining both into a single chart in your project? It could be optional hidden behind a flag. I could help with a pull request. Might be nice to even get this combined chart into the official chart repository in the future, too.

**Comment by steven-sheehy** [comment]
We ended up going with [MetalLB](https://metallb.universe.tf/) instead, so closing this.

**Comment by aledbf** [comment]
@steven-sheehy that makes sense. The current state of MetalLB is a better fit in a k8s cluster
