### ISSUE TITLE
bug: "ERROR: logging before flag.Parse" in all log messages

### ISSUE THREAD

**Issue by opusmagnum** [aledbf/kube-keepalived-vip#45]
All log messages from kube-keepalived-vip are prefixed with "ERROR: logging before flag.Parse".
For example:
```
ERROR: logging before flag.Parse: I0412 14:14:03.266668       1 keepalived.go:168] reloading keepalived
```
Most likely it comes from https://github.com/golang/glog/blob/master/glog.go#L680. Can it be fixed in kube-keepalived-vip?
Thanks in advance.

**Comment by aledbf** [comment]
Closing. Please update to 0.27
