### ISSUE TITLE
Accumulating haproxy-check.sh and curl zombies

### ISSUE THREAD

**Issue by elemental-lf** [aledbf/kube-keepalived-vip#66]
I'm seeing zombies from `haproxy-check.sh` and `curl` with release 0.29. I've about 125 of them on one node, mostly `curl`, some `haproxy-check.sh`. I'm currently not sure under what circumstances they occur but they don't seem to increase regularly. Regardless of the reason for this I think that `kube-keepalived-vip` either needs a zombie reaper (something like https://github.com/ramr/go-reaper) or `kube-keepalived-vip` needs to be started by `tini` or `dumb-init`. If we agree on one way or the other I could provide code.

**Comment by elemental-lf** [comment]
I'm going to implement the Go option now.

**Comment by aledbf** [comment]
@elemental-lf please use `dumb-init`
