### ISSUE TITLE
nopreempt is set along with priority weights?

### ISSUE THREAD

**Issue by mmiller1** [aledbf/kube-keepalived-vip#72]
We had an issue that caused our (custom) haproxy health checking scripts to fail on the MASTER, however, the VIP never failed over to another node.
After reading the keepalived docs, it appears that setting a priority weight on a health checking script will not cause keepalived to enter a FAULT state upon failure, but instead it will adjust the priority by the amount specified, which is fine, as long as keepalived is allowed to preempt the VIP to an instance with a higher priority. In the current template, it seems the only possible way for the VIP to ever fail over is to actually shut down the keepalived master instance. We fixed this by removing the weight from the check script, so now, as soon as the script fails (the number of times specified by the check "fall" value), the keepalived instance goes into FAULT, and the VIPs fail over.
My question is - was this possibly an oversight that you would like a PR for, or is this intentional and there's something I'm miss understanding here?

**Comment by aledbf** [comment]
Closing. Fixed in master
