### ISSUE TITLE
Help Needed: What's the difference than keepalived-vip in K8S repo

### ISSUE THREAD

**Issue by panpan0000** [aledbf/kube-keepalived-vip#83]
Hi, Dear  kube-keepalived-vip community:

Thanks for this fantastic project and putting those up .

As a starter seeking a nice  solution as substitution of kube-proxy (for layer-4 load-balance),
I've a general question ,which maybe others will have common question too
**What's the difference between this project and below one ?**
https://github.com/kubernetes/contrib/tree/master/keepalived-vip

**Comment by aledbf** [comment]
@panpan0000 this is the original project. After I started I continue in the contrib repository but at some point it was almost impossible to merge PRs, that's the reason why I returned the work to this repo

**Comment by panpan0000** [comment]
thank you , @aledbf !
