### ISSUE TITLE
HAProxy config not changed when endpoints change

### ISSUE THREAD

**Issue by josh-ferrell** [aledbf/kube-keepalived-vip#89]
When VIPs are in proxy mode haproxy isn't reloaded when the service endpoints change. This occurs whether a pod is restarted or a deployment is scaled. 

Currently using kube-keepalived-vip with 4 VIPs in configmap, all in PROXY mode.

**Comment by aledbf** [comment]
@josh-ferrell please make sure you are running v0.33
