### ISSUE TITLE
[issue-may-be] port or targetPort

### ISSUE THREAD

**Issue by panpan0000** [aledbf/kube-keepalived-vip#99]
in `pkg/controller/main.go`
func: `getServices`

since the `real_server` in `/etc/keepalived/keepalived.conf` is POD IP, instead of cluster IP,
so we should use `Spec.TargetPorts` instead of `Spec.Ports` ? 
since `TargetPort` is the container's port, and `Port` is the cluster IP port.(https://kubernetes.io/docs/concepts/services-networking/service/) 

```
for _, servicePort := range s.Spec.Ports {

}
```

**Comment by aledbf** [comment]
Closing. No, the definition in the configmap is about ports, no targetPorts. We lookup targetPorts in the `getEndpoints` function

**Comment by panpan0000** [comment]
oh, sorry for that. My bad

**Comment by panpan0000** [comment]
Hmm... 
I think I should point to this one:
```
			svcs = append(svcs, vip{
				Name:     ...
				IP:        ...
				Port:      int(servicePort.Port),  // --> here, should it be servicePort.TargetPort ?
				LVSMethod: ...,
				Backends:  ..,
				Protocol:  ...,
			})
```

https://github.com/aledbf/kube-keepalived-vip/blob/master/pkg/controller/main.go#L238
